# Generated by Django 5.0.2 on 2024-02-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_paid', models.FloatField(default=None)),
                ('payment_form', models.CharField(max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_refused', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(auto_now=True, null=True)),
                ('refused_at', models.DateTimeField(auto_now=True, null=True)),
                ('trip_customer_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.tripcustomer')),
            ],
        ),
    ]
